Cat Tinder API Validations
learn-academy-2022-bravo/cat-tinder-backend-earl-andrew pull request #3
Opened 2022-05-13 18:39 UTC by lundrew

2022-05-13 18:39 UTC, lundrew commented
Request to verify if we did the stretch challenges correctly.

2022-05-13 18:45 UTC, WalkerTexas-coder reviewed
left a comment with an example about how to do the update

2022-05-13 18:45 UTC, WalkerTexas-coder commented on spec/requests/cats_spec.rb
> +    end
Close! 
So the update should try to create an error
```ruby
it 'can't update an existing cat without a name' do
...
update_cat_params = {
        cat: {
          age: 2,
          enjoys: 'walk',
          image: 'http://www.catpics.com'
        }
      }
patch "/cats/#{cat.id}", params: update_cat_params
updated_cat = Cat.find(cat.id)
expect(response).to have_http_status(422)
json = JSON.parse(response.body)
expect(json['name']).to include "can't be blank"
```

2022-05-13 21:09 UTC, elysemontano requested changes
Changes needed for your model spec.

2022-05-13 21:09 UTC, elysemontano commented on spec/models/cat_spec.rb
> +    cat = Cat.create
What cat are you creating?  There will need to be attributes provided each time you create a cat.

2022-05-14 00:17 UTC, elysemontano requested changes
A few more changes in your tests.  Take a look at the comments.

2022-05-14 00:17 UTC, elysemontano commented on spec/models/cat_spec.rb
> +    cat = Cat.create enjoys: "Walks"
Still need the rest of the parameters when creating this cat.

2022-05-14 00:17 UTC, elysemontano commented on spec/requests/cats_spec.rb
> +      expect(json['name']).to include "can't be blank"
You should have a test for each attribute for update as well.

2022-05-16 17:19 UTC, sjproctor approved these changes

2022-05-16 17:19 UTC, sjproctor approved these changes

2022-05-16 17:24 UTC, elysemontano approved these changes

2022-05-16 19:46 UTC, merged